server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    # Identificador para sabermos que este é o Nginx do Docker
    add_header X-LAAC-Debug "Nginx-Container-Active" always;

    # Buffers estáveis
    client_header_buffer_size 1k;
    large_client_header_buffers 4 16k;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri.html $uri/ /index.html;
    }

    # Proxy API para o Orchestrator
    location /api/ {
        proxy_pass http://orq:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Garantir que erros de API não retornam o index.html
    location /api {
        proxy_pass http://orq:8000/;
        proxy_set_header Host $host;
    }
}
